# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-24 23:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.IntegerField(verbose_name='Código')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome')),
                ('data_cadastro', models.DateTimeField(verbose_name='Data de cadastro')),
            ],
        ),
    ]
