# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-25 15:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='cnpj',
            field=models.CharField(max_length=50, verbose_name='CNPJ'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='ie',
            field=models.CharField(default=1, max_length=50, verbose_name='inscrição estadual'),
            preserve_default=False,
        ),
    ]
