# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-25 16:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20171125_1310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fornecedor',
            name='tipo',
            field=models.IntegerField(choices=[(1, 'PESSOA FÍSICA'), (2, 'PESSOA JURÍDICA')], verbose_name='Tipo de pessoa'),
        ),
    ]
