# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-22 22:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_cliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='limite_compra',
            field=models.FloatField(verbose_name='limite de compra'),
        ),
    ]
