# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-25 18:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20171125_1404'),
    ]

    operations = [
        migrations.AddField(
            model_name='recebido',
            name='cliente',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.Fornecedor'),
            preserve_default=False,
        ),
    ]
