# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-25 19:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_recebido_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='recebido',
            name='foi_compensado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='recebido',
            name='foi_repassado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='recebido',
            name='tem_fundo',
            field=models.BooleanField(default=True),
        ),
    ]
