# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-23 00:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_fornecedor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fornecedor',
            old_name='cnpj',
            new_name='fax',
        ),
        migrations.RenameField(
            model_name='fornecedor',
            old_name='razao_social',
            new_name='nome',
        ),
        migrations.AddField(
            model_name='fornecedor',
            name='cpf_cnpj',
            field=models.CharField(default=1, max_length=50, verbose_name='CPF/CNPJ'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fornecedor',
            name='email',
            field=models.EmailField(default=1, max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fornecedor',
            name='ie',
            field=models.CharField(default=1, max_length=50, verbose_name='inscrição estadual'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fornecedor',
            name='responsavel',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fornecedor',
            name='rg',
            field=models.CharField(default=1, max_length=50, verbose_name='RG'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fornecedor',
            name='telefone',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
