# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-25 19:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20171125_1708'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recebido',
            name='emitente',
        ),
        migrations.AlterField(
            model_name='recebido',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Cliente'),
        ),
    ]
