# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-23 00:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20171122_2232'),
    ]

    operations = [
        migrations.AddField(
            model_name='fornecedor',
            name='tipo',
            field=models.IntegerField(choices=[(1, 'física'), (2, 'jurídica')], default=1, verbose_name='Tipo de pessoa'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fornecedor',
            name='responsavel',
            field=models.CharField(max_length=50, verbose_name='responsável'),
        ),
    ]
