# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-25 23:57
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20171125_1744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banco',
            name='data_cadastro',
            field=models.DateField(default=datetime.datetime(2017, 11, 25, 23, 57, 34, 673594, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='data_cadastro',
            field=models.DateField(default=datetime.datetime(2017, 11, 25, 23, 57, 34, 673594, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='emitido',
            name='data_cadastro',
            field=models.DateField(default=datetime.datetime(2017, 11, 25, 23, 57, 34, 677599, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='fornecedor',
            name='data_cadastro',
            field=models.DateField(default=datetime.datetime(2017, 11, 25, 23, 57, 34, 669591, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='recebido',
            name='data_cadastro',
            field=models.DateField(default=datetime.datetime(2017, 11, 25, 23, 57, 34, 677599, tzinfo=utc)),
        ),
    ]
