# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-23 00:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20171122_2236'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banco',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('telefone', models.CharField(max_length=50)),
                ('fax', models.CharField(max_length=50)),
                ('agencia', models.IntegerField(verbose_name='agência')),
                ('contato', models.CharField(max_length=50, verbose_name='pessoa de contato')),
            ],
        ),
        migrations.CreateModel(
            name='Terceiro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('negativado', models.BooleanField()),
                ('limite_compra', models.FloatField(verbose_name='limite de compra')),
                ('telefone', models.CharField(max_length=50)),
                ('cpf', models.CharField(max_length=50, verbose_name='CPF')),
                ('rg', models.CharField(max_length=50, verbose_name='RG')),
            ],
        ),
    ]
