# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-23 21:46
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_banco_terceiro'),
    ]

    operations = [
        migrations.AddField(
            model_name='banco',
            name='bairro',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='banco',
            name='cep',
            field=models.CharField(default=1, max_length=50, verbose_name='CEP'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='banco',
            name='cidade',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='banco',
            name='data_cadastro',
            field=models.DateField(default=datetime.datetime(2017, 11, 23, 21, 45, 55, 226646, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='banco',
            name='logradouro',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='banco',
            name='numero',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='banco',
            name='uf',
            field=models.CharField(default=1, max_length=2, verbose_name='UF'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fornecedor',
            name='tipo',
            field=models.IntegerField(choices=[(1, 'Física'), (2, 'Jurídica')], verbose_name='Tipo de pessoa'),
        ),
    ]
