# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-26 00:01
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20171125_2157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banco',
            name='data_cadastro',
            field=models.DateField(default=datetime.datetime(2017, 11, 26, 0, 1, 2, 23424, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='data_cadastro',
            field=models.DateField(default=datetime.datetime(2017, 11, 26, 0, 1, 2, 27449, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='emitido',
            name='data_cadastro',
            field=models.DateField(default=datetime.datetime(2017, 11, 26, 0, 1, 2, 31452, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='emitido',
            name='observacao',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fornecedor',
            name='data_cadastro',
            field=models.DateField(default=datetime.datetime(2017, 11, 26, 0, 1, 2, 23424, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='recebido',
            name='data_cadastro',
            field=models.DateField(default=datetime.datetime(2017, 11, 26, 0, 1, 2, 31452, tzinfo=utc)),
        ),
    ]
