# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-23 21:52
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20171123_1946'),
    ]

    operations = [
        migrations.AddField(
            model_name='fornecedor',
            name='bairro',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fornecedor',
            name='cep',
            field=models.CharField(default=1, max_length=50, verbose_name='CEP'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fornecedor',
            name='cidade',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fornecedor',
            name='data_cadastro',
            field=models.DateField(default=datetime.datetime(2017, 11, 23, 21, 52, 24, 541040, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fornecedor',
            name='logradouro',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fornecedor',
            name='numero',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fornecedor',
            name='uf',
            field=models.CharField(default=1, max_length=2, verbose_name='UF'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fornecedor',
            name='ie',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='inscrição estadual'),
        ),
        migrations.AlterField(
            model_name='fornecedor',
            name='rg',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='RG'),
        ),
    ]
