# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-23 21:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20171123_1952'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('cnpj', models.CharField(max_length=50, verbose_name='CPF/CNPJ')),
                ('ie', models.CharField(blank=True, max_length=50, null=True, verbose_name='inscrição estadual')),
                ('logradouro', models.CharField(max_length=50)),
                ('numero', models.IntegerField()),
                ('bairro', models.CharField(max_length=50)),
                ('cidade', models.CharField(max_length=50)),
                ('uf', models.CharField(max_length=2, verbose_name='UF')),
                ('cep', models.CharField(max_length=50, verbose_name='CEP')),
                ('telefone', models.CharField(max_length=50)),
                ('fax', models.CharField(max_length=50)),
            ],
        ),
    ]
