# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-26 15:55
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20171126_1351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banco',
            name='data_cadastro',
            field=models.DateField(default=datetime.datetime(2017, 11, 26, 15, 55, 11, 243667, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='data_cadastro',
            field=models.DateField(default=datetime.datetime(2017, 11, 26, 15, 55, 11, 243667, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='emitido',
            name='data_cadastro',
            field=models.DateField(default=datetime.datetime(2017, 11, 26, 15, 55, 11, 260403, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='fornecedor',
            name='data_cadastro',
            field=models.DateField(default=datetime.datetime(2017, 11, 26, 15, 55, 11, 243667, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='recebido',
            name='data_cadastro',
            field=models.DateField(default=datetime.datetime(2017, 11, 26, 15, 55, 11, 260403, tzinfo=utc)),
        ),
    ]
