# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-23 22:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20171123_2005'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cheque',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_cheque', models.IntegerField()),
                ('tipo', models.IntegerField(choices=[(1, 'Cheque Pré')])),
                ('data_entrada', models.DateField()),
                ('data_desconto', models.DateField()),
                ('valor', models.FloatField()),
                ('numero_nota', models.IntegerField()),
                ('observacao', models.TextField()),
                ('despesa', models.BooleanField()),
                ('data_cadastro', models.DateField()),
                ('banco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Banco')),
                ('fornecedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Fornecedor')),
            ],
        ),
    ]
