# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-26 15:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20171126_1356'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='limite_compra',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='negativado',
        ),
    ]
